name: AIN-blockchain CI/CD

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
    types: [opened, closed]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: pr
        run: |-
          echo "${{ github.event_name }}"
          echo "${{ github.event.action }}"
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.pull_request.base.ref }}"
          echo "${{ github.event_name }}"
  performance_test:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Triggered Test
        run: |-
          echo "Triggered"
          echo "head:${{ github.event.pull_request.head.ref }}"
          echo "base:${{ github.event.pull_request.base.ref }}"
